variable "builds" {
  type = list(
    object(
      {
        name            = string,
        builder_type    = string,
        build_time      = number,
        artifact_id     = string,
        packer_run_uuid = string
      }
    )
  )
  description = "List of images, as generated by Packer's 'Manifest' post-processor."
}

variable "last_run_uuid" {
  type = string
}

locals {
  local_data = jsondecode(file("${path.module}/packer.auto.tfvars.json"))
}

output "show_locals" {
  value = local.local_data.builds[0].artifact_id
}

output "show_image" {
  value = split(":", element(var.builds, 0).artifact_id)[0]
}
