FROM alpine:3.6
RUN apk update --no-cache \
    && apk add --no-cache ruby ruby-dev ruby-bundler build-base \
    && gem install bundler -v 2.3.26 --no-rdoc --no-ri \
    && rm -rf /var/cache/apk/*

ENV APP_HOME /app
RUN mkdir $APP_HOME

WORKDIR $APP_HOME

ADD Gemfile* ./
RUN bundle install
ADD . $APP_HOME

ENV POST_SERVICE_HOST post_db
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment_db
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
