---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "comment.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: {{ .Values.service.externalPort }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: reddit
    component: ui
    release: {{ .Release.Name }}
