version: '3'
services:
  zipkin:
    image: openzipkin/zipkin:2.21.0
    ports:
      - "9411:9411"
  fluent-bit:
    image: ${USERNAME}/fluent-bit:${FLUENT_VERSION}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.17.3
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.17.3
    ports:
      - "5601:5601"
