---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: reddit
    component: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: reddit
        component: mongo
    spec:
      restartPolicy: Always
      containers:
      - name: mongo
        image: mongo:4.4.24
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: 512Mi
            cpu: 1
        volumeMounts:
        - name: mongo-ps
          mountPath: /data/db
      volumes:
      - name: mongo-ps
        persistentVolumeClaim:
          claimName: mongo-pvc
