---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: reddit
    component: {{ .Values.labels.component }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: reddit
      component: {{ .Values.labels.component }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: comment
      labels:
        app: reddit
        component: {{ .Values.labels.component }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: comment
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          limits:
            memory: 256Mi
            cpu: "1"
        env:
        - name: COMMENT_DATABASE_HOST
          value: {{ .Values.env.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
