---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "comment.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: reddit
    component: {{ .Values.labels.component }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: reddit
    component: {{ .Values.labels.component }}
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
